// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import AddressController from "./address_controller.js"
application.register("address", AddressController)

import MenuController from "./menu_controller.js"
application.register("menu", MenuController)

import VoteController from "./vote_controller.js"
application.register("vote", VoteController)

import WalletController from "./wallet_controller.js"
application.register("wallet", WalletController)
